# Generated by Django 5.0.8 on 2024-08-16 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task'),
        ),
    ]
